[package]
name = "gettext-rs"
description = "GNU Gettext FFI binding for Rust"
version = "0.1.0"
authors = ["Konstantin Salikhov <koka58@yandex.ru>"]
repository = "https://github.com/Koka/gettext-rs"

